language: node_js
node_js: "10.15"
cache: yarn

_production-job: &production-job
  stage: production
  name: SERVICE_NAME
  script: scripts/deploy.js SERVICE_NAME
  install: skip
  env:
    - "ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm"

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - <<: *production-job
      stage: production-started
      name: Deployment Started
      script: npx @parameter1/base-cms-website-deployment-tool notify-started

    #############################
    ### vvv ADD SITES HERE vvv ##
    #############################

    - <<: *production-job
      name: automationworld.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy automationworld.com websites

    - <<: *production-job
      name: healthcarepackaging.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy healthcarepackaging.com websites

    - <<: *production-job
      name: oemmagazine.org
      script: npx @parameter1/base-cms-website-deployment-tool deploy oemmagazine.org websites

    - <<: *production-job
      name: packworld.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy packworld.com websites

    - <<: *production-job
      name: profoodworld.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy profoodworld.com websites

    - <<: *production-job
      name: cobotspot.packworld.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy cobotspot.packworld.com websites

    #############################
    ### ^^^ ADD SITES HERE ^^^ ##
    #############################

    - <<: *production-job
      stage: production-finished
      name: Deployment Finished
      script: npx @parameter1/base-cms-website-deployment-tool notify-finished
