language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  - name: staging-started
    if: tag is present
  - name: staging
    if: tag is present
  - name: staging-finished
    if: tag is present

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=staging]

    #############################
    ### vvv ADD SITES HERE vvv ##
    #############################

    - stage: production
      name: automationworld.com
      script: npx @base-cms/website-deployment-tool deploy automationworld.com websites
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging
      name: automationworld.com
      script: npx @base-cms/website-deployment-tool deploy automationworld.com staging-websites-tauron
      install: skip
      env: [ENVIRONMENT=staging]

    - stage: production
      name: healthcarepackaging.com
      script: npx @base-cms/website-deployment-tool deploy healthcarepackaging.com websites
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging
      name: healthcarepackaging.com
      script: npx @base-cms/website-deployment-tool deploy healthcarepackaging.com staging-websites-tauron
      install: skip
      env: [ENVIRONMENT=staging]

    - stage: production
      name: oemmagazine.org
      script: npx @base-cms/website-deployment-tool deploy oemmagazine.org websites
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging
      name: oemmagazine.org
      script: npx @base-cms/website-deployment-tool deploy oemmagazine.org staging-websites-tauron
      install: skip
      env: [ENVIRONMENT=staging]

    - stage: production
      name: packworld.com
      script: npx @base-cms/website-deployment-tool deploy packworld.com websites
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging
      name: packworld.com
      script: npx @base-cms/website-deployment-tool deploy packworld.com staging-websites-tauron
      install: skip
      env: [ENVIRONMENT=staging]

    - stage: production
      name: profoodworld.com
      script: npx @base-cms/website-deployment-tool deploy profoodworld.com websites
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging
      name: profoodworld.com
      script: npx @base-cms/website-deployment-tool deploy profoodworld.com staging-websites-tauron
      install: skip
      env: [ENVIRONMENT=staging]

    - stage: production
      name: cobotspot.packworld.com
      script: npx @base-cms/website-deployment-tool deploy cobotspot.packworld.com websites
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging
      name: cobotspot.packworld.com
      script: npx @base-cms/website-deployment-tool deploy cobotspot.packworld.com staging-websites-tauron
      install: skip
      env: [ENVIRONMENT=staging]

    #############################
    ### ^^^ ADD SITES HERE ^^^ ##
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=production]

    - stage: staging-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=staging]
