language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: notify_start
    if: tag is present
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=test

    - stage: notify_start
      script: deploy/notify-start.sh
      install: skip

    - stage: notify
      script: deploy/notify.sh
      install: skip

    - stage: deploy
      name: Automation World
      script: deploy/index.js automationworld caprica
      install: skip

    - stage: deploy
      name: Packaging World
      script: deploy/index.js packworld caprica
      install: skip

    - stage: deploy
      name: Healthcare Packaging
      script: deploy/index.js healthcarepackaging caprica
      install: skip

    - stage: deploy
      name: Pro Food World
      script: deploy/index.js profoodworld caprica
      install: skip

    - stage: deploy
      name: OEM Magazine
      script: deploy/index.js oemmagazine caprica
      install: skip
