version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.24
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  GTM_CONTAINER_ID: ${GTM_CONTAINER_ID}
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  OMEDA_APP_ID: ${OMEDA_APP_ID-(unset)}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-(unset)}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.tauron.base.parameter1.com/graphql}
  # @todo the recaptcha values should be removed (?) once contact-us is moved to core.
  RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY-(unset)}
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  GLOBAL_50_250_DOCS_API_KEY: ${GLOBAL_50_250_DOCS_API_KEY-(unset)}
  # @todo the sendgrid values should be removed once the @parameter1/base-cms-mailer service is created.
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  ENABLE_IDENTITY_X: ${ENABLE_IDENTITY_X-1}

  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://tauron.graphql.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://tauron.oembed.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://tauron.rss.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://tauron.sitemaps.base.parameter1.com}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10002}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10013}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10011}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10009}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  aw:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/automationworld.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9709
      LIVERELOAD_PORT: 19709
      TENANT_KEY: pmmi_all
      SITE_ID: 5d88cecaf175132c008b4567
    ports:
      - "9709:80"
      - "19709:19709"

  pw:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/packworld.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9711
      LIVERELOAD_PORT: 19711
      TENANT_KEY: pmmi_all
      SITE_ID: 5d88cedef175132c008b456b
    ports:
      - "9711:80"
      - "19711:19711"

  hcp:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/healthcarepackaging.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9712
      LIVERELOAD_PORT: 19712
      TENANT_KEY: pmmi_all
      SITE_ID: 5d88cef7f175132c008b456f
    ports:
      - "9712:80"
      - "19712:19712"

  pfw:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/profoodworld.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9713
      LIVERELOAD_PORT: 19713
      TENANT_KEY: pmmi_all
      SITE_ID: 5d88cf1af175132c008b4577
    ports:
      - "9713:80"
      - "19713:19713"

  oem:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/oemmagazine.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9714
      LIVERELOAD_PORT: 19714
      TENANT_KEY: pmmi_all
      SITE_ID: 5d88cf05f175132c008b4573
    ports:
      - "9714:80"
      - "19714:19714"

  mundo:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/mundopmmi.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9716
      LIVERELOAD_PORT: 19716
      TENANT_KEY: pmmi_mundo
      SITE_ID: 5d0a748572c1aa35008b4567
      LEADERS_ALIAS: leaders/2021
    ports:
      - "9716:80"
      - "19716:19716"

  mundo-global:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/global.mundopmmi.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9716
      LIVERELOAD_PORT: 19716
      TENANT_KEY: pmmi_mundo
      SITE_ID: 5d0a748572c1aa35008b4567
      LEADERS_ALIAS: leaders/2021
    ports:
      - "9716:80"
      - "19716:19716"
