name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 5d88cecaf175132c008b4567, dir: automationworld.com, stack: tauron, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-automationworld.com }
          - { id: 5d88cef7f175132c008b456f, dir: healthcarepackaging.com, stack: tauron, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-healthcarepackaging.com }
          - { id: 5d0a748572c1aa35008b4567, dir: mundopmmi.com, stack: tauron, account: pmmi, tenant: pmmi_mundo, rancher_label: pmmi-media-group-mundopmmi.com }
          - { id: 5d88cf05f175132c008b4573, dir: oemmagazine.org, stack: tauron, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-oemmagazine.org }
          - { id: 5d88cedef175132c008b456b, dir: packworld.com, stack: tauron, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-packworld.com }
          - { id: 5d88cf1af175132c008b4577, dir: profoodworld.com, stack: tauron, account: pmmi, tenant: pmmi_all, rancher_label: pmmi-media-group-profoodworld.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: website-${{ matrix.site.dir }}
      site_id: ${{ matrix.site.id }}
      site_host: ${{ matrix.site.dir }}
      infra_stack: ${{ matrix.site.stack }}
      tenant_key: ${{ matrix.site.tenant }}
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
